const ENEMY_BOSSES = [
  {
    key: "iron-colossus",
    label: "钢垒兽",
    description: "重甲怪兽，先垒盾稳场，再把护盾轰成重击。",
    avatar: "垒",
    maxHp: 40,
    baseEp: 2,
    skills: [
      {
        key: "plate-up",
        name: "装甲抬升",
        cost: 1,
        type: "防御",
        kind: "defend",
        block: 6,
        summary: "6点护盾",
        description: "获得6点护盾",
        accent: "defend",
        artLabel: "装甲",
        cooldown: 0,
      },
      {
        key: "ram-strike",
        name: "盾角冲撞",
        cost: 2,
        type: "进攻",
        kind: "attack",
        damage: 5,
        block: 2,
        summary: "5点伤害并获得2点护盾",
        description: "对敌方造成5点伤害，并获得2点护盾",
        accent: "attack",
        artLabel: "冲撞",
        cooldown: 0,
      },
      {
        key: "fortress-regrowth",
        name: "钢层再构",
        cost: 1,
        type: "修复",
        kind: "defend",
        block: 3,
        statusEffects: [{ target: "actor", key: "regen", stacks: 2 }],
        summary: "3点护盾并获得2层再生",
        description: "获得3点护盾，并获得2层再生",
        accent: "defend",
        artLabel: "再构",
        cooldown: 3,
      },
      {
        key: "siege-heart",
        name: "攻城心核",
        cost: 2,
        type: "核心",
        kind: "attack",
        damage: 0,
        convertEffects: [{ source: "actor", resource: "shield", mode: "all", target: "target", to: "damage" }],
        summary: "消耗全部护盾，造成等同护盾值的伤害",
        description: "消耗自身全部护盾，对敌方造成等同于消耗护盾值的伤害",
        accent: "attack",
        artLabel: "心核",
        cooldown: 3,
      },
      {
        key: "ground-shaker",
        name: "震地碾压",
        cost: 3,
        type: "终结",
        kind: "attack",
        damage: 8,
        summary: "8点伤害",
        description: "对敌方造成8点伤害",
        accent: "attack",
        artLabel: "震地",
        cooldown: 4,
      },
    ],
  },
  {
    key: "shadow-reaver",
    label: "掠杀号兽",
    description: "高速怪兽，偷能滚节奏，再把余能倾泻成处决伤害。",
    avatar: "掠",
    maxHp: 34,
    baseEp: 2,
    skills: [
      {
        key: "shadow-stab",
        name: "掠影突刺",
        cost: 0,
        type: "攻击",
        kind: "attack",
        damage: 1,
        summary: "1点伤害",
        description: "对敌方造成1点伤害",
        accent: "attack",
        artLabel: "突刺",
        cooldown: 0,
      },
      {
        key: "cheap-shot",
        name: "廉价狠击",
        cost: 1,
        type: "攻击",
        kind: "attack",
        damage: 3,
        summary: "3点伤害",
        description: "对敌方造成3点伤害",
        accent: "attack",
        artLabel: "狠击",
        cooldown: 0,
      },
      {
        key: "smoke-shell",
        name: "烟幕后撤",
        cost: 1,
        type: "防御",
        kind: "defend",
        block: 3,
        energyGain: 1,
        cleanseEffects: [{ target: "actor", kind: "debuff", count: 1 }],
        summary: "3点护盾，回复1点能量并清除1个减益",
        description: "获得3点护盾，回复1点能量，并清除自身1个减益状态",
        accent: "defend",
        artLabel: "烟幕",
        cooldown: 1,
      },
      {
        key: "loot-spark",
        name: "顺手夺能",
        cost: 1,
        type: "回能",
        kind: "energize",
        damage: 1,
        energyGain: 1,
        statusEffects: [{ target: "target", key: "poison", stacks: 1 }],
        summary: "1点伤害，回复1点能量并施加1层中毒",
        description: "对敌方造成1点伤害，回复1点能量，并施加1层中毒",
        accent: "energize",
        artLabel: "夺能",
        cooldown: 2,
      },
      {
        key: "blood-rush",
        name: "血性冲锋",
        cost: 2,
        type: "攻击",
        kind: "attack",
        damage: 5,
        energyGain: 1,
        summary: "5点伤害并回复1点能量",
        description: "对敌方造成5点伤害，并回复1点能量",
        accent: "attack",
        artLabel: "冲锋",
        cooldown: 1,
      },
      {
        key: "reaver-judgement",
        name: "劫掠处决",
        cost: 2,
        type: "核心",
        kind: "attack",
        damage: 2,
        convertEffects: [{ source: "actor", resource: "energy", mode: "all", target: "target", to: "damage", multiplier: 2 }],
        summary: "消耗剩余能量，造成每点2点外加2点伤害",
        description: "消耗自身剩余全部能量，对敌方造成每点能量2点外加2点的伤害",
        accent: "attack",
        artLabel: "处决",
        cooldown: 3,
      },
    ],
  },
  {
    key: "reactor-beast",
    label: "熔核兽",
    description: "热能怪兽，持续挂虚弱拆节奏，再把失衡目标直接爆轰。",
    avatar: "熔",
    maxHp: 36,
    baseEp: 2,
    skills: [
      {
        key: "heat-surge",
        name: "热流喷发",
        cost: 1,
        type: "回能",
        kind: "energize",
        block: 2,
        energyGain: 1,
        summary: "2点护盾并回复1点能量",
        description: "获得2点护盾，并回复1点能量",
        accent: "energize",
        artLabel: "热流",
        cooldown: 0,
      },
      {
        key: "fuse-bolt",
        name: "熔芯栓击",
        cost: 1,
        type: "攻击",
        kind: "attack",
        damage: 2,
        energyGain: 1,
        statusEffects: [{ target: "target", key: "weaken", stacks: 1, duration: 2 }],
        summary: "2点伤害，回复1点能量并施加1层虚弱",
        description: "对敌方造成2点伤害，回复1点能量，并施加1层虚弱",
        accent: "attack",
        artLabel: "栓击",
        cooldown: 0,
      },
      {
        key: "pressure-valve",
        name: "压阀泄放",
        cost: 2,
        type: "攻击",
        kind: "attack",
        damage: 4,
        block: 2,
        statusEffects: [{ target: "target", key: "weaken", stacks: 1, duration: 2 }],
        summary: "4点伤害并获得2点护盾，施加1层虚弱",
        description: "对敌方造成4点伤害，获得2点护盾，并施加1层虚弱",
        accent: "attack",
        artLabel: "压阀",
        cooldown: 2,
      },
      {
        key: "boiler-rush",
        name: "锅炉突进",
        cost: 2,
        type: "攻击",
        kind: "attack",
        damage: 5,
        block: 2,
        energyGain: 0,
        cleanseEffects: [{ target: "target", kind: "buff", count: 1 }],
        summary: "5点伤害并获得2点护盾，驱散1个增益",
        description: "对敌方造成5点伤害，获得2点护盾，同时驱散敌方1个增益状态",
        accent: "attack",
        artLabel: "锅炉",
        cooldown: 2,
      },
      {
        key: "imbalance-burst",
        name: "失衡爆轰",
        cost: 2,
        type: "核心",
        kind: "attack",
        damage: 1,
        statusBurstEffects: [{ source: "target", key: "weaken", mode: "all", target: "target", to: "damage", multiplier: 4 }],
        summary: "引爆全部虚弱，造成每层4点外加1点伤害",
        description: "引爆敌方全部虚弱，对敌方造成每层4点外加1点的伤害",
        accent: "attack",
        artLabel: "爆轰",
        cooldown: 3,
      },
    ],
  },
  {
    key: "venom-broodmother",
    label: "毒蚀母兽",
    description: "毒雾怪兽，快速叠高中毒，再把毒层一次性引爆。",
    avatar: "毒",
    maxHp: 35,
    baseEp: 2,
    skills: [
      {
        key: "acid-prick",
        name: "酸刺",
        cost: 0,
        type: "攻击",
        kind: "attack",
        damage: 1,
        statusEffects: [{ target: "target", key: "poison", stacks: 1 }],
        summary: "1点伤害并施加1层中毒",
        description: "对敌方造成1点伤害，并施加1层中毒",
        accent: "attack",
        artLabel: "酸刺",
        cooldown: 0,
      },
      {
        key: "rot-feed",
        name: "腐殖喂养",
        cost: 1,
        type: "攻击",
        kind: "attack",
        damage: 2,
        statusEffects: [{ target: "target", key: "poison", stacks: 2 }],
        summary: "2点伤害并施加2层中毒",
        description: "对敌方造成2点伤害，并施加2层中毒",
        accent: "attack",
        artLabel: "腐殖",
        cooldown: 0,
      },
      {
        key: "venom-husk",
        name: "毒壳包覆",
        cost: 1,
        type: "防御",
        kind: "defend",
        block: 4,
        statusEffects: [{ target: "target", key: "poison", stacks: 1 }],
        summary: "4点护盾并施加1层中毒",
        description: "获得4点护盾，并施加1层中毒",
        accent: "defend",
        artLabel: "毒壳",
        cooldown: 1,
      },
      {
        key: "toxin-reflux",
        name: "毒液回流",
        cost: 1,
        type: "回能",
        kind: "energize",
        energyGain: 1,
        statusEffects: [{ target: "target", key: "poison", stacks: 1 }],
        summary: "回复1点能量并施加1层中毒",
        description: "回复1点能量，并施加1层中毒",
        accent: "energize",
        artLabel: "回流",
        cooldown: 2,
      },
      {
        key: "miasma-flood",
        name: "病瘴漫灌",
        cost: 2,
        type: "防御",
        kind: "defend",
        block: 3,
        statusEffects: [{ target: "target", key: "poison", stacks: 3 }],
        summary: "3点护盾并施加3层中毒",
        description: "获得3点护盾，并施加3层中毒",
        accent: "defend",
        artLabel: "病瘴",
        cooldown: 2,
      },
      {
        key: "toxin-detonator",
        name: "毒囊爆裂",
        cost: 2,
        type: "核心",
        kind: "attack",
        damage: 1,
        statusBurstEffects: [{ source: "target", key: "poison", mode: "all", target: "target", to: "damage", multiplier: 2 }],
        summary: "引爆全部中毒，造成每层2点外加1点伤害",
        description: "引爆敌方全部中毒，对敌方造成每层2点外加1点的伤害",
        accent: "attack",
        artLabel: "爆裂",
        cooldown: 3,
      },
    ],
  },
];

function getBossProfile(bossKey) {
  return ENEMY_BOSSES.find((boss) => boss.key === bossKey) || null;
}

function getRandomBossProfile() {
  return ENEMY_BOSSES[Math.floor(Math.random() * ENEMY_BOSSES.length)];
}

function getBossProfiles() {
  return ENEMY_BOSSES.slice();
}

module.exports = {
  getBossProfile,
  getBossProfiles,
  getRandomBossProfile,
};
