const SELF_ARCHETYPES = [
  {
    key: "blade-dance",
    label: "疾刃流",
    description: "低费连段铺锐势，再用核心斩击一口收束。",
    templates: [
      {
        key: "quick-cut",
        name: "快切",
        cost: 0,
        type: "攻击",
        kind: "attack",
        damage: 3,
        summary: "3点伤害",
        description: "对敌方造成3点伤害",
        accent: "attack",
        artLabel: "快切",
        art: null,
      },
      {
        key: "twin-drive",
        name: "双刃驱动",
        cost: 1,
        type: "连击",
        kind: "attack",
        damage: 5,
        energyGain: 1,
        summary: "5点伤害并回复1点能量",
        description: "对敌方造成5点伤害，并回复1点能量",
        accent: "attack",
        artLabel: "双刃",
        art: null,
      },
      {
        key: "sidestep-guard",
        name: "侧步架盾",
        cost: 1,
        type: "防御",
        kind: "defend",
        block: 5,
        energyGain: 1,
        summary: "5点护盾并回复1点能量",
        description: "获得5点护盾，并回复1点能量",
        accent: "defend",
        artLabel: "侧步",
        art: null,
      },
      {
        key: "focus-prism",
        name: "聚能棱镜",
        cost: 1,
        type: "回能",
        kind: "energize",
        energyGain: 2,
        statusEffects: [{ target: "actor", key: "sharpness", stacks: 2, permanent: true }],
        summary: "回复2点能量并获得2层永久锐势",
        description: "回复2点能量，并获得2层永久锐势",
        accent: "energize",
        artLabel: "棱镜",
        art: null,
      },
      {
        key: "pulse-barrage",
        name: "起势连斩",
        cost: 2,
        type: "攻击",
        kind: "attack",
        damage: 6,
        statusEffects: [{ target: "actor", key: "sharpness", stacks: 1, permanent: true }],
        summary: "6点伤害并获得1层永久锐势",
        description: "对敌方造成6点伤害，并获得1层永久锐势",
        accent: "attack",
        artLabel: "起势",
        art: null,
      },
      {
        key: "spinning-guardblade",
        name: "回旋护刃",
        cost: 2,
        type: "技法",
        kind: "attack",
        damage: 7,
        block: 5,
        summary: "7点伤害并获得5点护盾",
        description: "对敌方造成7点伤害，并获得5点护盾",
        accent: "attack",
        artLabel: "护刃",
        art: null,
      },
      {
        key: "overload-slash",
        name: "刃镜归一",
        cost: 2,
        type: "核心",
        kind: "attack",
        damage: 4,
        statusBurstEffects: [{ source: "actor", key: "sharpness", mode: "all", target: "target", to: "damage", multiplier: 5 }],
        summary: "引爆全部锐势，造成每层5点外加4点伤害",
        description: "引爆自身全部锐势，对敌方造成每层5点外加4点的伤害",
        accent: "attack",
        artLabel: "归一",
        art: null,
      },
      {
        key: "compressed-barrier",
        name: "压缩护幕",
        cost: 1,
        type: "防御",
        kind: "defend",
        block: 9,
        summary: "9点护盾",
        description: "获得9点护盾",
        accent: "defend",
        artLabel: "护幕",
        art: null,
      },
    ],
  },
  {
    key: "bastion-loop",
    label: "壁阵流",
    description: "先堆护盾，再靠核心牌把护盾一次性砸成爆发伤害。",
    templates: [
      {
        key: "shield-tap",
        name: "盾击试探",
        cost: 1,
        type: "防反",
        kind: "attack",
        damage: 4,
        block: 4,
        summary: "4点伤害并获得4点护盾",
        description: "对敌方造成4点伤害，并获得4点护盾",
        accent: "defend",
        artLabel: "盾击",
        art: null,
      },
      {
        key: "brace-core",
        name: "稳固核心",
        cost: 1,
        type: "防御",
        kind: "defend",
        block: 8,
        summary: "8点护盾",
        description: "获得8点护盾",
        accent: "defend",
        artLabel: "稳固",
        art: null,
      },
      {
        key: "counter-surge",
        name: "反冲脉冲",
        cost: 2,
        type: "反击",
        kind: "attack",
        damage: 6,
        block: 6,
        summary: "6点伤害并获得6点护盾",
        description: "对敌方造成6点伤害，并获得6点护盾",
        accent: "defend",
        artLabel: "反冲",
        art: null,
      },
      {
        key: "reactive-charge",
        name: "净化回路",
        cost: 1,
        type: "净化",
        kind: "energize",
        heal: 5,
        cleanseEffects: [{ target: "actor", kind: "debuff", count: 99 }],
        summary: "回复5点生命并清除所有减益",
        description: "回复5点生命，并清除自身所有减益状态",
        accent: "energize",
        artLabel: "净化",
        art: null,
      },
      {
        key: "mirror-bunker",
        name: "镜面掩体",
        cost: 2,
        type: "防御",
        kind: "defend",
        block: 14,
        summary: "14点护盾",
        description: "获得14点护盾",
        accent: "defend",
        artLabel: "掩体",
        art: null,
      },
      {
        key: "ram-wall",
        name: "冲阵壁",
        cost: 2,
        type: "进攻",
        kind: "attack",
        damage: 8,
        block: 4,
        summary: "8点伤害并获得4点护盾",
        description: "对敌方造成8点伤害，并获得4点护盾",
        accent: "attack",
        artLabel: "冲壁",
        art: null,
      },
      {
        key: "fortress-break",
        name: "垒盾倾轰",
        cost: 2,
        type: "核心",
        kind: "attack",
        damage: 4,
        convertEffects: [{ source: "actor", resource: "shield", mode: "all", target: "target", to: "damage" }],
        summary: "消耗全部护盾，造成护盾值加4的伤害",
        description: "消耗自身全部护盾，对敌方造成等同于消耗护盾值外加4点的伤害",
        accent: "attack",
        artLabel: "倾轰",
        art: null,
      },
      {
        key: "resonance-shell",
        name: "谐振再生",
        cost: 1,
        type: "防御",
        kind: "defend",
        block: 5,
        statusEffects: [{ target: "actor", key: "regen", stacks: 2 }],
        summary: "5点护盾并获得2层再生",
        description: "获得5点护盾，并获得2层再生",
        accent: "defend",
        artLabel: "谐振",
        art: null,
      },
    ],
  },
  {
    key: "overclock-burst",
    label: "超载流",
    description: "先囤能，再把剩余能量一次性过载成爆发伤害。",
    templates: [
      {
        key: "spark-lance",
        name: "火花枪",
        cost: 1,
        type: "攻击",
        kind: "attack",
        damage: 5,
        summary: "5点伤害",
        description: "对敌方造成5点伤害",
        accent: "attack",
        artLabel: "火花",
        art: null,
      },
      {
        key: "capacitor-shift",
        name: "电容切换",
        cost: 0,
        type: "回能",
        kind: "energize",
        block: 2,
        energyGain: 2,
        summary: "2点护盾并回复2点能量",
        description: "获得2点护盾，并回复2点能量",
        accent: "energize",
        artLabel: "电容",
        art: null,
      },
      {
        key: "charge-buckler",
        name: "蓄能偏折",
        cost: 1,
        type: "防御",
        kind: "defend",
        block: 7,
        energyGain: 1,
        summary: "7点护盾并回复1点能量",
        description: "获得7点护盾，并回复1点能量",
        accent: "defend",
        artLabel: "偏折",
        art: null,
      },
      {
        key: "surge-step",
        name: "跃流步",
        cost: 1,
        type: "技法",
        kind: "attack",
        damage: 4,
        energyGain: 2,
        summary: "4点伤害并回复2点能量",
        description: "对敌方造成4点伤害，并回复2点能量",
        accent: "attack",
        artLabel: "跃流",
        art: null,
      },
      {
        key: "ion-hammer",
        name: "离子锤",
        cost: 2,
        type: "攻击",
        kind: "attack",
        damage: 9,
        summary: "9点伤害",
        description: "对敌方造成9点伤害",
        accent: "attack",
        artLabel: "离子",
        art: null,
      },
      {
        key: "booster-bloom",
        name: "推进绽放",
        cost: 1,
        type: "回能",
        kind: "energize",
        block: 4,
        energyGain: 3,
        summary: "4点护盾并回复3点能量",
        description: "获得4点护盾，并回复3点能量",
        accent: "energize",
        artLabel: "推进",
        art: null,
      },
      {
        key: "nova-rupture",
        name: "超载新星",
        cost: 2,
        type: "核心",
        kind: "attack",
        damage: 6,
        convertEffects: [{ source: "actor", resource: "energy", mode: "all", target: "target", to: "damage", multiplier: 4 }],
        summary: "消耗剩余能量，造成每点4点外加6点伤害",
        description: "消耗自身剩余全部能量，对敌方造成每点能量4点外加6点的伤害",
        accent: "attack",
        artLabel: "新星",
        art: null,
      },
      {
        key: "voltage-break",
        name: "伏特断裂",
        cost: 2,
        type: "攻击",
        kind: "attack",
        damage: 7,
        energyGain: 1,
        summary: "7点伤害并回复1点能量",
        description: "对敌方造成7点伤害，并回复1点能量",
        accent: "attack",
        artLabel: "断裂",
        art: null,
      },
    ],
  },
  {
    key: "venom-burst",
    label: "毒爆流",
    description: "大量叠毒，靠核心件把中毒层数瞬间引爆。",
    templates: [
      {
        key: "toxin-needle",
        name: "刺毒针",
        cost: 0,
        type: "攻击",
        kind: "attack",
        damage: 1,
        statusEffects: [{ target: "target", key: "poison", stacks: 3 }],
        summary: "1点伤害并施加3层中毒",
        description: "对敌方造成1点伤害，并施加3层中毒",
        accent: "attack",
        artLabel: "毒针",
        art: null,
      },
      {
        key: "seep-circuit",
        name: "渗毒回路",
        cost: 1,
        type: "攻击",
        kind: "attack",
        damage: 3,
        statusEffects: [{ target: "target", key: "poison", stacks: 4 }],
        summary: "3点伤害并施加4层中毒",
        description: "对敌方造成3点伤害，并施加4层中毒",
        accent: "attack",
        artLabel: "渗毒",
        art: null,
      },
      {
        key: "mire-film",
        name: "毒沼护膜",
        cost: 1,
        type: "防御",
        kind: "defend",
        block: 6,
        statusEffects: [{ target: "target", key: "poison", stacks: 2 }],
        summary: "6点护盾并施加2层中毒",
        description: "获得6点护盾，并施加2层中毒",
        accent: "defend",
        artLabel: "护膜",
        art: null,
      },
      {
        key: "distill-charge",
        name: "萃毒回充",
        cost: 1,
        type: "回能",
        kind: "energize",
        energyGain: 2,
        statusEffects: [{ target: "target", key: "poison", stacks: 3 }],
        summary: "回复2点能量并施加3层中毒",
        description: "回复2点能量，并施加3层中毒",
        accent: "energize",
        artLabel: "萃毒",
        art: null,
      },
      {
        key: "chronic-erosion",
        name: "慢性侵蚀",
        cost: 1,
        type: "攻击",
        kind: "attack",
        damage: 4,
        statusEffects: [{ target: "target", key: "poison", stacks: 3 }],
        summary: "4点伤害并施加3层中毒",
        description: "对敌方造成4点伤害，并施加3层中毒",
        accent: "attack",
        artLabel: "侵蚀",
        art: null,
      },
      {
        key: "miasma-hoard",
        name: "瘴雾囤积",
        cost: 2,
        type: "防御",
        kind: "defend",
        block: 5,
        statusEffects: [{ target: "target", key: "poison", stacks: 5 }],
        summary: "5点护盾并施加5层中毒",
        description: "获得5点护盾，并施加5层中毒",
        accent: "defend",
        artLabel: "瘴雾",
        art: null,
      },
      {
        key: "catalyst-blast",
        name: "催化爆鸣",
        cost: 2,
        type: "核心",
        kind: "attack",
        damage: 4,
        statusBurstEffects: [{ source: "target", key: "poison", mode: "all", target: "target", to: "damage", multiplier: 3 }],
        summary: "引爆全部中毒，造成每层3点外加4点伤害",
        description: "引爆敌方全部中毒，对敌方造成每层3点外加4点的伤害",
        accent: "attack",
        artLabel: "爆鸣",
        art: null,
      },
      {
        key: "venom-heart",
        name: "剧毒穿心",
        cost: 3,
        type: "终结",
        kind: "attack",
        damage: 8,
        statusEffects: [{ target: "target", key: "poison", stacks: 4 }],
        summary: "8点伤害并施加4层中毒",
        description: "对敌方造成8点伤害，并施加4层中毒",
        accent: "attack",
        artLabel: "穿心",
        art: null,
      },
    ],
  },
];

const ENEMY_ARCHETYPES = [
  {
    key: "iron-fortress",
    label: "壁垒流",
    description: "厚甲推进，先垒盾续航，再用核心牌兑现护盾爆发。",
    templates: [
      {
        key: "bulwark-up",
        name: "壁垒加固",
        cost: 1,
        type: "防御",
        kind: "defend",
        block: 8,
        summary: "8点护盾",
        description: "获得8点护盾",
        accent: "defend",
        artLabel: "壁垒",
        art: null,
      },
      {
        key: "furnace-reload",
        name: "炉芯回充",
        cost: 1,
        type: "回能",
        kind: "energize",
        block: 3,
        energyGain: 1,
        summary: "3点护盾并回复1点能量",
        description: "获得3点护盾，并回复1点能量",
        accent: "energize",
        artLabel: "炉芯",
        art: null,
      },
      {
        key: "suppression-volley",
        name: "压制齐射",
        cost: 2,
        type: "攻击",
        kind: "attack",
        damage: 6,
        summary: "6点伤害",
        description: "对敌方造成6点伤害",
        accent: "attack",
        artLabel: "齐射",
        art: null,
      },
      {
        key: "iron-crush",
        name: "钢铁碾压",
        cost: 2,
        type: "攻击",
        kind: "attack",
        damage: 8,
        summary: "8点伤害",
        description: "对敌方造成8点伤害",
        accent: "attack",
        artLabel: "碾压",
        art: null,
      },
      {
        key: "counter-bastion",
        name: "反击棱堡",
        cost: 2,
        type: "防御",
        kind: "defend",
        damage: 3,
        block: 6,
        summary: "3点伤害并获得6点护盾",
        description: "对敌方造成3点伤害，并获得6点护盾",
        accent: "defend",
        artLabel: "棱堡",
        art: null,
      },
      {
        key: "charged-cannon",
        name: "棱堡倾轰",
        cost: 2,
        type: "核心",
        kind: "attack",
        damage: 2,
        convertEffects: [{ source: "actor", resource: "shield", mode: "all", target: "target", to: "damage" }],
        summary: "消耗全部护盾，造成护盾值加2的伤害",
        description: "消耗自身全部护盾，对敌方造成等同于消耗护盾值外加2点的伤害",
        accent: "attack",
        artLabel: "倾轰",
        art: null,
      },
      {
        key: "frontline-push",
        name: "战线推进",
        cost: 1,
        type: "进攻",
        kind: "attack",
        damage: 2,
        block: 4,
        summary: "2点伤害并获得4点护盾",
        description: "对敌方造成2点伤害，并获得4点护盾",
        accent: "attack",
        artLabel: "推进",
        art: null,
      },
      {
        key: "combat-charge",
        name: "战备充能",
        cost: 1,
        type: "回能",
        kind: "energize",
        block: 2,
        energyGain: 1,
        statusEffects: [{ target: "actor", key: "regen", stacks: 2 }],
        summary: "2点护盾，回复1点能量并获得2层再生",
        description: "获得2点护盾，回复1点能量，并获得2层再生",
        accent: "energize",
        artLabel: "充能",
        art: null,
      },
    ],
  },
  {
    key: "raider-flurry",
    label: "掠袭流",
    description: "轻甲快攻，先偷能抢节奏，再用核心件把余能一口倾泻。",
    templates: [
      {
        key: "knife-run",
        name: "掠影突刺",
        cost: 0,
        type: "攻击",
        kind: "attack",
        damage: 2,
        summary: "2点伤害",
        description: "对敌方造成2点伤害",
        accent: "attack",
        artLabel: "突刺",
        art: null,
      },
      {
        key: "cheap-shot",
        name: "廉价狠击",
        cost: 1,
        type: "攻击",
        kind: "attack",
        damage: 4,
        summary: "4点伤害",
        description: "对敌方造成4点伤害",
        accent: "attack",
        artLabel: "狠击",
        art: null,
      },
      {
        key: "smoke-lean",
        name: "烟幕后撤",
        cost: 1,
        type: "防御",
        kind: "defend",
        block: 4,
        energyGain: 1,
        cleanseEffects: [{ target: "actor", kind: "debuff", count: 1 }],
        summary: "4点护盾，回复1点能量并清除1个减益",
        description: "获得4点护盾，回复1点能量，并清除自身1个减益状态",
        accent: "defend",
        artLabel: "烟幕",
        art: null,
      },
      {
        key: "quick-loot",
        name: "顺手夺能",
        cost: 1,
        type: "回能",
        kind: "energize",
        damage: 2,
        energyGain: 2,
        statusEffects: [{ target: "target", key: "poison", stacks: 2 }],
        summary: "2点伤害，回复2点能量并施加2层中毒",
        description: "对敌方造成2点伤害，回复2点能量，并施加2层中毒",
        accent: "energize",
        artLabel: "夺能",
        art: null,
      },
      {
        key: "cross-cut",
        name: "交叉撕裂",
        cost: 2,
        type: "攻击",
        kind: "attack",
        damage: 7,
        summary: "7点伤害",
        description: "对敌方造成7点伤害",
        accent: "attack",
        artLabel: "交叉",
        art: null,
      },
      {
        key: "raid-guard",
        name: "掠阵格挡",
        cost: 1,
        type: "防御",
        kind: "defend",
        damage: 2,
        block: 4,
        summary: "2点伤害并获得4点护盾",
        description: "对敌方造成2点伤害，并获得4点护盾",
        accent: "defend",
        artLabel: "掠阵",
        art: null,
      },
      {
        key: "blood-rush",
        name: "血性冲锋",
        cost: 2,
        type: "攻击",
        kind: "attack",
        damage: 7,
        energyGain: 1,
        summary: "7点伤害并回复1点能量",
        description: "对敌方造成7点伤害，并回复1点能量",
        accent: "attack",
        artLabel: "冲锋",
        art: null,
      },
      {
        key: "finisher-pounce",
        name: "劫掠处决",
        cost: 1,
        type: "核心",
        kind: "attack",
        damage: 3,
        convertEffects: [{ source: "actor", resource: "energy", mode: "all", target: "target", to: "damage", multiplier: 3 }],
        summary: "消耗剩余能量，造成每点3点外加3点伤害",
        description: "消耗自身剩余全部能量，对敌方造成每点能量3点外加3点的伤害",
        accent: "attack",
        artLabel: "处决",
        art: null,
      },
    ],
  },
  {
    key: "core-overdrive",
    label: "熔芯流",
    description: "先挂虚弱拆增益，再用爆轰处决失衡目标。",
    templates: [
      {
        key: "heat-surge",
        name: "热流喷发",
        cost: 1,
        type: "回能",
        kind: "energize",
        block: 3,
        energyGain: 2,
        summary: "3点护盾并回复2点能量",
        description: "获得3点护盾，并回复2点能量",
        accent: "energize",
        artLabel: "热流",
        art: null,
      },
      {
        key: "ember-shell",
        name: "余烬护壳",
        cost: 1,
        type: "防御",
        kind: "defend",
        block: 5,
        summary: "5点护盾",
        description: "获得5点护盾",
        accent: "defend",
        artLabel: "余烬",
        art: null,
      },
      {
        key: "fuse-bolt",
        name: "熔芯栓击",
        cost: 1,
        type: "攻击",
        kind: "attack",
        damage: 3,
        energyGain: 1,
        statusEffects: [{ target: "target", key: "weaken", stacks: 1, duration: 2 }],
        summary: "3点伤害，回复1点能量并施加1层虚弱",
        description: "对敌方造成3点伤害，回复1点能量，并施加1层虚弱",
        accent: "attack",
        artLabel: "栓击",
        art: null,
      },
      {
        key: "pressure-valve",
        name: "压阀泄放",
        cost: 2,
        type: "攻击",
        kind: "attack",
        damage: 5,
        block: 3,
        statusEffects: [{ target: "target", key: "weaken", stacks: 2, duration: 2 }],
        summary: "5点伤害并获得3点护盾，施加2层虚弱",
        description: "对敌方造成5点伤害，获得3点护盾，并施加2层虚弱",
        accent: "attack",
        artLabel: "压阀",
        art: null,
      },
      {
        key: "burner-kick",
        name: "燃烧踢",
        cost: 2,
        type: "攻击",
        kind: "attack",
        damage: 6,
        statusEffects: [{ target: "target", key: "weaken", stacks: 1, duration: 2 }],
        summary: "6点伤害并施加1层虚弱",
        description: "对敌方造成6点伤害，并施加1层虚弱",
        accent: "attack",
        artLabel: "燃踢",
        art: null,
      },
      {
        key: "meltdown-brace",
        name: "过热支架",
        cost: 1,
        type: "防御",
        kind: "defend",
        block: 3,
        energyGain: 2,
        summary: "3点护盾并回复2点能量",
        description: "获得3点护盾，并回复2点能量",
        accent: "energize",
        artLabel: "过热",
        art: null,
      },
      {
        key: "boiler-rush",
        name: "锅炉突进",
        cost: 2,
        type: "攻击",
        kind: "attack",
        damage: 7,
        block: 2,
        energyGain: 1,
        cleanseEffects: [{ target: "target", kind: "buff", count: 1 }],
        summary: "7点伤害并获得2点护盾，回复1点能量，驱散1个增益",
        description: "对敌方造成7点伤害，获得2点护盾，并回复1点能量，同时驱散敌方1个增益状态",
        accent: "attack",
        artLabel: "锅炉",
        art: null,
      },
      {
        key: "reactor-burst",
        name: "失衡爆轰",
        cost: 2,
        type: "核心",
        kind: "attack",
        damage: 2,
        statusBurstEffects: [{ source: "target", key: "weaken", mode: "all", target: "target", to: "damage", multiplier: 6 }],
        summary: "引爆全部虚弱，造成每层6点外加2点伤害",
        description: "引爆敌方全部虚弱，对敌方造成每层6点外加2点的伤害",
        accent: "attack",
        artLabel: "爆轰",
        art: null,
      },
    ],
  },
  {
    key: "venom-fang",
    label: "毒蚀流",
    description: "快速把毒层堆高，再靠核心牌瞬间引爆。",
    templates: [
      {
        key: "acid-prick",
        name: "酸刺",
        cost: 0,
        type: "攻击",
        kind: "attack",
        damage: 1,
        statusEffects: [{ target: "target", key: "poison", stacks: 2 }],
        summary: "1点伤害并施加2层中毒",
        description: "对敌方造成1点伤害，并施加2层中毒",
        accent: "attack",
        artLabel: "酸刺",
        art: null,
      },
      {
        key: "rot-feed",
        name: "腐殖喂养",
        cost: 1,
        type: "攻击",
        kind: "attack",
        damage: 2,
        statusEffects: [{ target: "target", key: "poison", stacks: 3 }],
        summary: "2点伤害并施加3层中毒",
        description: "对敌方造成2点伤害，并施加3层中毒",
        accent: "attack",
        artLabel: "腐殖",
        art: null,
      },
      {
        key: "venom-husk",
        name: "毒壳包覆",
        cost: 1,
        type: "防御",
        kind: "defend",
        block: 5,
        statusEffects: [{ target: "target", key: "poison", stacks: 1 }],
        summary: "5点护盾并施加1层中毒",
        description: "获得5点护盾，并施加1层中毒",
        accent: "defend",
        artLabel: "毒壳",
        art: null,
      },
      {
        key: "toxin-reflux",
        name: "毒液回流",
        cost: 1,
        type: "回能",
        kind: "energize",
        energyGain: 2,
        statusEffects: [{ target: "target", key: "poison", stacks: 2 }],
        summary: "回复2点能量并施加2层中毒",
        description: "回复2点能量，并施加2层中毒",
        accent: "energize",
        artLabel: "回流",
        art: null,
      },
      {
        key: "sour-flense",
        name: "蚀骨剐裂",
        cost: 1,
        type: "攻击",
        kind: "attack",
        damage: 3,
        statusEffects: [{ target: "target", key: "poison", stacks: 2 }],
        summary: "3点伤害并施加2层中毒",
        description: "对敌方造成3点伤害，并施加2层中毒",
        accent: "attack",
        artLabel: "剐裂",
        art: null,
      },
      {
        key: "blight-fog",
        name: "病瘴漫灌",
        cost: 2,
        type: "防御",
        kind: "defend",
        block: 4,
        statusEffects: [{ target: "target", key: "poison", stacks: 4 }],
        summary: "4点护盾并施加4层中毒",
        description: "获得4点护盾，并施加4层中毒",
        accent: "defend",
        artLabel: "病瘴",
        art: null,
      },
      {
        key: "toxin-detonator",
        name: "毒囊爆裂",
        cost: 2,
        type: "核心",
        kind: "attack",
        damage: 2,
        statusBurstEffects: [{ source: "target", key: "poison", mode: "all", target: "target", to: "damage", multiplier: 2 }],
        summary: "引爆全部中毒，造成每层2点外加2点伤害",
        description: "引爆敌方全部中毒，对敌方造成每层2点外加2点的伤害",
        accent: "attack",
        artLabel: "爆裂",
        art: null,
      },
      {
        key: "grave-venom",
        name: "尸毒灌心",
        cost: 3,
        type: "终结",
        kind: "attack",
        damage: 6,
        statusEffects: [{ target: "target", key: "poison", stacks: 3 }],
        summary: "6点伤害并施加3层中毒",
        description: "对敌方造成6点伤害，并施加3层中毒",
        accent: "attack",
        artLabel: "尸毒",
        art: null,
      },
    ],
  },
];

const ARCHETYPES_BY_OWNER = {
  self: SELF_ARCHETYPES,
  enemy: ENEMY_ARCHETYPES,
};

function getOwnerArchetypes(ownerId) {
  return ARCHETYPES_BY_OWNER[ownerId] || SELF_ARCHETYPES;
}

function getDeckArchetype(ownerId, archetypeKey) {
  return getOwnerArchetypes(ownerId).find((archetype) => archetype.key === archetypeKey) || null;
}

function getRandomDeckArchetype(ownerId) {
  const archetypes = getOwnerArchetypes(ownerId);

  if (!archetypes.length) {
    throw new Error(`No deck archetypes configured for ${ownerId}`);
  }

  return archetypes[Math.floor(Math.random() * archetypes.length)];
}

function getCardTemplate(ownerId, serial = 1, archetypeKey) {
  const safeSerial = Math.max(1, Number(serial) || 1);
  const archetype =
    getDeckArchetype(ownerId, archetypeKey) ||
    getOwnerArchetypes(ownerId)[0];
  const templates = archetype.templates || [];

  if (!templates.length) {
    throw new Error(`No card templates configured for ${ownerId}:${archetype?.key || "unknown"}`);
  }

  return templates[(safeSerial - 1) % templates.length];
}

module.exports = {
  getCardTemplate,
  getDeckArchetype,
  getOwnerArchetypes,
  getRandomDeckArchetype,
};
